import StyledComponentsRegistry from "@/utils/lib/registry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "UbCare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body>
        <StyledComponentsRegistry>
          <Provider>{children}</Provider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
